version: 2.1

orbs:
  win: circleci/windows@5.1.0

jobs:
  build-linux:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo apt update
            sudo apt install -y build-essential cmake gcc clang g++ libssl-dev libboost-all-dev libcurl4-openssl-dev

      - run:
          name: Build Project
          command: |
            mkdir -p build
            cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
            cmake --build build --target jella -- -j $(nproc)

      - run:
          name: Export Executable
          command: |
            mkdir -p ~/export
            cp build/bin/jella ~/export/jella

      - store_artifacts:
          path: ~/export
          destination: artifacts


  build-windows:
    executor: win/server-2022
    steps:
      - checkout
      - run:
          name: Setup MSYS2 & toolchain
          command: |
            choco install -y msys2
            C:\tools\msys64\usr\bin\bash -lc "
              pacman -Syu --noconfirm
              pacman -S --noconfirm mingw-w64-x86_64-toolchain \
                                       mingw-w64-x86_64-cmake \
                                       mingw-w64-x86_64-make \
                                       mingw-w64-x86_64-ninja \
                                       mingw-w64-x86_64-openssl
            "
      - run:
          name: Build Project
          shell: C:/tools/msys64/usr/bin/bash -lc
          command: |
            mkdir -p build
            cmake -S . -B build -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release
            cmake --build build --target jella -- -j $(nproc)
      - run:
          name: Export Executable
          shell: C:/tools/msys64/usr/bin/bash -lc
          command: |
            cp build/bin/jella.exe C:/export/jella.exe
      - store_artifacts:
          path: C:/export
          destination: artifacts

workflows:
  build:
    jobs:
      - build-linux
      - build-windows